# Generated by Django 4.1.1 on 2023-10-25 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cieQQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0)),
                ('ques', models.FileField(null=True, upload_to='')),
                ('duration', models.IntegerField(default=0)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('on', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ok.course')),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ok.department')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ok.semester')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ok.session')),
            ],
        ),
    ]
