# Generated by Django 4.1.1 on 2023-10-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ok', '0003_cieqa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cieq',
            old_name='CLO1',
            new_name='clo1',
        ),
        migrations.RenameField(
            model_name='cieq',
            old_name='CLO3',
            new_name='clo3',
        ),
        migrations.RenameField(
            model_name='cieq',
            old_name='CLO4',
            new_name='clo4',
        ),
        migrations.RenameField(
            model_name='cieq',
            old_name='CLO5',
            new_name='clo5',
        ),
        migrations.RenameField(
            model_name='cieq',
            old_name='CLO6',
            new_name='clo6',
        ),
        migrations.AddField(
            model_name='cieq',
            name='no',
            field=models.IntegerField(default=0),
        ),
    ]
