# Generated by Django 4.1.1 on 2023-10-26 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ok', '0005_rename_clo2_cieq_clo2_semqa'),
    ]

    operations = [
        migrations.CreateModel(
            name='semQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clo1', models.FileField(null=True, upload_to='')),
                ('clo2', models.FileField(null=True, upload_to='')),
                ('clo3', models.FileField(null=True, upload_to='')),
                ('clo4', models.FileField(null=True, upload_to='')),
                ('clo5', models.FileField(null=True, upload_to='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ok.course')),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ok.department')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ok.semester')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ok.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ok.student')),
            ],
        ),
    ]
