from django.contrib import admin

# Register your models here.
from .models import *
admin.site.register(Session)
admin.site.register(Student)
admin.site.register(Teacher)
admin.site.register(Committee)
admin.site.register(Course)
admin.site.register(Semester)
admin.site.register(CIE)
admin.site.register(Final)
admin.site.register(CombinedResult)
admin.site.register(Tutorial)
admin.site.register(nonSem)
admin.site.register(nonCombined)
admin.site.register(Staff)
admin.site.register(semResult)
admin.site.register(Message)
admin.site.register(Department)
admin.site.register(indAttendance)
admin.site.register(bestOf)
admin.site.register(nonBestOf)
admin.site.register(indLab)
admin.site.register(Assignment)
admin.site.register(copp)
admin.site.register(cieQQ)
admin.site.register(cieQ)
admin.site.register(cieQA)
admin.site.register(semQA)
admin.site.register(semQ)